name: test

on:
  pull_request:
  push:
    branches:
      - 'main'

jobs:
  test:
    runs-on: macos-12
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: swift test
